spring:
  application:
    name: helix-health
  datasource:
    url: jdbc:h2:file:./data/helixhealth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080
